<?php

/**
 * @file
 * Primary module hooks for Custom Help module.
 */

/**
 * Implements hook_theme().
 */
function custom_helppage_theme() {

  $moduleHandler = \Drupal::service('module_handler');

  // List Entity-Types
  // https://www.hashbangcode.com/article/drupal-9-get-list-content-types
  $entityTypeManager = \Drupal::service('entity_type.manager');
  $types = [];
  $contentTypes = $entityTypeManager->getStorage('node_type')->loadMultiple();
  foreach ($contentTypes as $contentType) {
    $types[$contentType->id()] = $contentType->label();
  }

  // $paragraphs = ParagraphsType::loadMultiple();
  // $accordion = array_key_exists("accordion", $paragraphs);

  $modulepath = \Drupal::service('extension.list.module')->getPath('custom_helppage');
  $blog = (array_key_exists("article", $types) && \Drupal::currentUser()->hasPermission('create article content'));
  $book = (array_key_exists("book", $types) && \Drupal::currentUser()->hasPermission('create book content'));
  $blockedit = \Drupal::currentUser()->hasPermission('update any paragraphs block content');
  $host = \Drupal::request()->getSchemeAndHttpHost();
  $company_mail = \Drupal::config('custom_company_token.settings')->get('mail');
  $site_mail = \Drupal::config('system.site')->get('mail');
  $private = \Drupal::service('file_system')->realpath("private://");
  $assets = '/'.$modulepath.'/assets';
  $publicfiles = '/sites/default/files/helppage';
  $contactform = $moduleHandler->moduleExists('contact');
  $contactformmail = $contactform ? \Drupal::config('contact.form.side_wide')->get('recipients')[0] : '';

  return [
    'custom-helppage-user' => [
      'variables' => [
      'blog' => $blog,
      'blockedit' => $blockedit,
      'host' => $host,
      'modulepath' => $modulepath,
      'assets' => $assets,
      'publicfiles' => $publicfiles,
    ],],
    'custom-helppage-admin' => [
      'variables' => [
        'host' => $host,
        'email' => $company_mail,
        'sitemail' => $site_mail,
        'privatepath' => $private,
        'contactform' => $contactform,
        'contactformmail' => $contactformmail,
        'domain' => str_replace('http://','',$GLOBALS['base_url']),
      ],],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function custom_helppage_page_attachments(array &$attachments) {
  // Only attach CSS file to the "/admin/help" path.
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/admin/adminhelp' || $current_path == '/admin/userhelp') {
    $attachments['#attached']['library'][] = 'custom_helppage/custom_helppage.pages';
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function custom_helppage_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'custom_helppage/custom_helppage.tree';
}
